### PR TITLE
set associated head sha on pull request event

### LINKED ISSUE #206: Use correct commit sha for PRs?
### Behaviour

Hey folks, similar to https://github.com/docker/metadata-action/issues/191 a bit, when running a workflow on a PR event, the `{{ sha }}` refers to the temporary merge commit to the target branch, not the commit that was pushed to trigger the event.

I realize this is a pretty common situation with GitHub actions, but it ends up with Docker tags/labels that don't map back to any real commits. It would be really useful if this action automatically used `github.event.pull_request.head.sha` for PR events. I think it would have to be set for the tags `{{ sha }}` value and the auto-generated label `org.opencontainers.image.revision`.

I'm aware we can work around the tags situation by using `type=raw` and passing a value based on `github.event.pull_request.head.sha`, but it feels a bit error-prone.

I'm unaware of a workaround for overriding the `org.opencontainers.image.revision` label, though.

#### Steps to reproduce this issue

See example workflow and run on a PR

#### Expected behaviour

Tags with the correct sha in a PR (same with org.opencontainers.image.revision label)

#### Actual behaviour

Tags are created with the merge commit of the PR to the target branch (same with org.opencontainers.image.revision)

```yml
name: AWS

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: "my-repo/my-image"
          tags: |
            type=ref,event=branch,suffix=-{{ sha }}
            type=ref,event=pr,suffix=-{{ sha }}
```

### PR DESCRIPTION
**Pull request by crazy-max**
fixes #206

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

**Comment by gustavovalverde** [comment]
This might seem as a fix in versioning, but it's a breaking change. For example, this breaks all our workflows which depend on the built image `sha`

Now we have to include extra conditions as the sha won't be the same when there's a PR and a push to `main`. It would have been nice to increase the version to `5.0.0` considering this would break most scenarios being based on `GITHUB_SHA` or $`{{ github.sha }}`

This now requires implementations to use `( ${{ github.event.pull_request.head.sha }} || {{ github.sha }} )` for a single pull to work on both GitHub events (PRs and push)

**Comment by crazy-max** [comment]
@gustavovalverde From what I see on https://github.com/ZcashFoundation/zebra/pull/5390, you're pushing an image on PR and others jobs depend on it using `github.sha` as tag.

I didn't think about this use case as pushing on PR is not possible in majority of cases as secrets can't be exposed. But in your case I see you're using `google-github-actions/auth` action to connect to your provider using the OIDC token so you're able to push to its registry.

Even if you can [share image between jobs](https://github.com/docker/build-push-action/blob/master/docs/advanced/share-image-jobs.md) without pushing them, it still sounds like a valid use case to use a registry. I will revert this change, sorry about that.

File: src/meta.ts [hunk 1]
```diff
@@ -37,6 +37,10 @@ export class Meta {
       context.ref = `refs/pull/${context.payload.number}/merge`;
     }
 
+    if ((/pull_request/.test(context.eventName) || /pull_request_target/.test(context.eventName)) && context.payload?.pull_request?.head?.sha != undefined) {
```
Comment (dimaqq) [inline src/meta.ts:40]: This appears to check that substring “pull_request” appears anywhere in the event name. Maybe the intention was to check if the name starts with a certain substring? Or matches exactly if that’s the entire event name?
